export const FETCH_LAUNCHES_INIT = "FETCH_LAUNCHES_INIT";
export const FETCH_LAUNCHES_SUCCESS = "FETCH_LAUNCHES_SUCCESS";
export const FETCH_LAUNCHES_FAIL = "FETCH_LAUNCHES_FAIL";

export const FETCH_LAUNCH_DETAIL_INIT = "FETCH_LAUNCH_DETAIL_INIT"
export const FETCH_LAUNCH_DETAIL_SUCCESS = "FETCH_LAUNCH_DETAIL_SUCCESS";
export const FETCH_LAUNCH_DETAIL_FAIL = "FETCH_LAUNCH_DETAIL_FAIL";